buildAutomation/startupEverything.sh, docker-compose.yaml, frontend/reel-rating-display-service/.dockerignore, frontend/reel-rating-display-service/.gitignore, frontend/reel-rating-display-service/.mvn/wrapper/maven-wrapper.properties, frontend/reel-rating-display-service/Dockerfile, frontend/reel-rating-display-service/README.txt, frontend/reel-rating-display-service/mvnw, frontend/reel-rating-display-service/mvnw.cmd, frontend/reel-rating-display-service/pom.xml, frontend/reel-rating-display-service/src/main/java/edu/oswego/cs/rest/DisplayController.java, frontend/reel-rating-display-service/src/main/java/edu/oswego/cs/rest/RestApplication.java, frontend/reel-rating-display-service/src/main/liberty/config/server.xml
Adds the reel-rating-display-service and updates the build file to include it.
=> Add reel-rating-display-service

backend/reel-rating-auth-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-auth-service/src/main/java/edu/oswego/cs/rest/LoginService.java
Updates the login service to properly set a users login time. This pull request also provides the first iteration of Java Docs in the login service class. A commit for creating the setUserDateTime was also created for use in the log service.
=> Update login service

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
Added createFlag(), createReview(), createActor(), createMovie() have all been started.
=> Create CRUD operations 

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Actor.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Flag.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Movie.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
added create endpoints
- createFlag
- createMovie
- createActor
- createReview
added get endpoints
- getMoviesWithFlagName
- getMoviesWithRatingCategoryName
- getMoviesWithActorName
- getMovieByName
- getActorByName
- getReviewsByMovieName
- getReviewsByUser
Added Flag JsonClass
Edited Movie and Actor Json Class
Eddited DatabaseController to remove movieIds in verifying since Mongo will do that book keeping for us.
=> create and get endpoints

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
Removes unused code and fixes create movie to allow movies with the same name to be created. This commit follows a merge request which disallowed this feature.
=> Remove unused code

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Rating.java
reformatted and changed the createRating to account for upperbounds.
Added comments and javadocs to the Database Controller to help organize and separate groups of methods. More will need to be added at a later date, especially within the update and delete sections
=> createRating edits and Database controller javadocs

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Rating.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Review.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
reviewTitle removed since it is not in the requirements.
Added a datetime of creation to the reviews and ratings to allow for sorting by new or other similar functionality
=> remove reviewTitle add dateTimeCreated   

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
Changed all mentions of Flags to Tags. Added comments to help organize and explain the new image methods
=> Flag -> Tag and image docs

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
Sorts the movie database and returns the first 10 in order of recent release. The number of item returns is defined in the method, but can be easily changed or moved to a parameter.
Intended to be called when loading the homepage.
=> Added getRecentReleaseMovies() to database controller

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
reworked createTag to include usernames, privacy, and movieIds
edited endpoint for createTags
added endpoint for getRecentReleaseMovies and editted the DatabaseController method to take the number to return as a parameter and the return a list of movies not documents.
This should fix Issue #84 since the tagNames got a serious rework. If this still does not resolve the problem we will keep hunting.
=> createTag and getRecentReleaseMovies

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Review.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
This merge resolves issue #81.
=> Fix issue #81

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Actor.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
Resolves issue #82 by setting actors movie ids and ensuring all of the actors information is read from the database.
=> update actors to have list of movie ids

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
Resolves Issue #83 but not requires an actorId instead of name
=> swap principalCast to contains actor ids instead of names

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
Also resolves a typo causing issue #81
=> create data population endpoint

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
was having a casting issue in getRecentRelaseMovie method of DatabaseController (as noted in issue #96).
No longer casting a MongoIterable to ArrayList.
Added better comments and layout of method as well
=> fixed getRecentReleaseMovies

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/PopulationData.java
Split PopulateData class method into smaller methods by movies. I did have to move the creation of actors from the end of the file to within their appropriate movie. 
Added more documentation and comments throughout the DatabseController and endpoints. 
createRating now checks to make sure that the rating the user is making has not already been attached to the movie.
=> de-monolith PopulateData class, documentation, and createRating tweak 

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Movie.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/PopulationData.java
recentReleaseMovies now returns the aggregated most popular rating, and three tags for home page/ movie card display
=> edits to recentReleaseMovies endpoints 

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Movie.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
attachedFlags is now an ArrayList of strings instead of a stringed version of the ArrayList
=> fixed attachedTags

backend/reel-rating-auth-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-auth-service/src/main/java/edu/oswego/cs/rest/LoginService.java, backend/reel-rating-auth-service/src/main/java/edu/oswego/cs/rest/User.java
Adds emails to the user's service as well as regex matching in the login service.
=> Add Email to user's database, add regex for email

backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/ActorDataService.java, backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/RatingDataService.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/ReviewDataService.java
Split movie data microservice into separate micro services for
- Movies 
- Ratings/Tags
- Reviews
- Actors
The Movie dataservice is still rather messy and bloated due to how we are populating data. We will continue to trim the fat as we can.
=> De-monolithing the MovieData micro service 

backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/ActorDataService.java, backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
This merge resolves Issue #136 by fixing a typo with principalCast.
=> Fix for getActorsWithMovieId

frontend/reel-rating-display-service/src/main/webapp/js/home.js, frontend/reel-rating-display-service/src/main/webapp/views/home.html
Take two on this. I seen a couple changes its possible I just didn't save all the files before sending before
=> Resubmit to check for the home page

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
=> Issue #135

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
Fixes Issue #149 by adding authentication and checking if the movie id is valid. If the movie id is invalid a 404 is sent.
=> update movie image endpoint

backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/ActorDataService.java, backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Actor.java, backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/JSession.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/JSession.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Rating.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/RatingDataService.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/JSession.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Review.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/ReviewDataService.java
Added JSession rewrite for actor, ratings, and review microservices
=> JSession rewrite 

frontend/reel-rating-display-service/src/main/webapp/js/globalRef.js, frontend/reel-rating-display-service/src/main/webapp/js/home.js
Updates how the frontend handles requests to facilitate the new sessions. Also enables the local frontend to connect to the deployed backend.
=> Update for local frontend development

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java
added getMovieWithMovieId endpoint that returns the movie with the given Mongo HexId or null if not found
=> getMovieWithMovieId added

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
Forgot the database controller portion now it should work
=> adding database controller method for getmovieWithMovieId

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/RatingDataService.java
Tags now contain a field "state" which can be "upvote" or "downvote". Upon creation it is automatically set to "upvote" and can be updated at a later time. When upvoting or downvoting if you do not have a tag a tag is created in the users name and assigned the correct state. 
Fixed issue #141 so getRatingWithSameNameAndUpperbound should be set as well as getRatingsWithSameName. Also added getRatingsWithUpperbound which is pretty useless, but was mostly a sanity check.
=> Upvote/Downvote tags and getRating fixes 

backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/ActorDataService.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/ReviewDataService.java
threw in some mulitline comments to help organize data service files. Also made small edits to endpoint names for consistency. 
Please do not accept this unless you are david to avoid conflicts and not completely screw some connections between front and backend
=> documentation and endpoint consistency ONLY DAVID CONFIRM

backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Tag.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/RatingDataService.java
Added two endpoints getTagState and getTagScoresForMovieModal
`getTagState` can be used to check the state of a given tag from a movie for the requester. It returns a string either "upvote", "downvote", or "noTag"
`getTagScoresForMovieModal` returns a list of unique tags for a given movie. Each tag contains its name, the aggregated totalScore of the upvotes and downvotes, and its state. The state is whether it is upvote, downvoted, or neither from the user making the request. This endpoint is meant to be called when loading the movie modal to populate the tag portion. The tags are sent in descending order based on total score so the highest scored tags come first
=> tag endpoints getTagStatus and getTagScoresForMovieModal

frontend/reel-rating-display-service/src/main/webapp/js/controller.js, frontend/reel-rating-display-service/src/main/webapp/js/home.js, frontend/reel-rating-display-service/src/main/webapp/views/home.html
These changes resolve the movie image portion of Issue #191 and the movie carousel moving on its own portion of Issue #199.
=> fix for carousel automatic sliding and accessibility image alt text

frontend/reel-rating-display-service/src/main/webapp/views/home.html
Resolves issue #197, aside from the up/down vote creation that needs to be reworked.
=> create review button hanged to submit review

frontend/reel-rating-display-service/src/main/webapp/js/controller.js, frontend/reel-rating-display-service/src/main/webapp/js/home.js
Adds JSDocs to help improve the workflow for the gui team.
=> Add JSDocs

frontend/reel-rating-display-service/src/main/webapp/js/controller.js, frontend/reel-rating-display-service/src/main/webapp/js/home.js, frontend/reel-rating-display-service/src/main/webapp/js/login.js, frontend/reel-rating-display-service/src/main/webapp/js/networkReq.js
Added some JS docs, moved logic out of the controller, and reduced some allocation
=> General Code Maintaince

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/JsonClasses/Rating.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/RatingDataService.java
added endpoint used to populate the ratings portion of the rate movie modal. returns a list of Rating objects representing all the unique rating categories (combos of ratingName and upperbound) attached to a movie. If the requester has already rated the movie in one of the categories their rating is included as well in the userRating field.
=> added getUniqueRatingCategoriesAndUserRatingWithMovieId

backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
now when the createRating endpoint is hit and the user has already created a rating with this upperbound and ratingName instead of doing nothing the userRating is now updated.
=> createRating updates userRating 

frontend/reel-rating-display-service/src/main/webapp/js/home.js, frontend/reel-rating-display-service/src/main/webapp/js/webComps/progress-bar-clickable.js
Adds a network post request to the clickable progress bars and updates the network get request for the clickable progress bars to use the new endpoint "getUniqueRatingCategoriesAndUserRatingWithMovieId"
=> Update network requests for clickable progress bars

frontend/reel-rating-display-service/src/main/webapp/css/global.css, frontend/reel-rating-display-service/src/main/webapp/js/controller.js, frontend/reel-rating-display-service/src/main/webapp/js/globalRef.js, frontend/reel-rating-display-service/src/main/webapp/js/home.js, frontend/reel-rating-display-service/src/main/webapp/js/jsStyles.js, frontend/reel-rating-display-service/src/main/webapp/js/networkReq.js, frontend/reel-rating-display-service/src/main/webapp/js/tools.js, frontend/reel-rating-display-service/src/main/webapp/js/webComps/progress-bar-clickable.js, frontend/reel-rating-display-service/src/main/webapp/js/webComps/title-with-line.js, frontend/reel-rating-display-service/src/main/webapp/views/home.html
Make the edits necessary and don't worry about breaking stuff. We can fix it later if need be
=> Basic search with new modal

.idea/.gitignore, .idea/OZ-CSC-480-HCI-521-Fall-2023-.iml, .idea/compiler.xml, .idea/encodings.xml, .idea/jarRepositories.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-search-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-search-service/src/main/java/edu/oswego/cs/rest/SearchService.java
search beside by rating and tag name now return all info needed to make the rating cards. The two mentioned search endpoints will compile, but do not function
=> fixed movie preview info return

backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
Saves the frontend from having to balance the movie id.
=> set movieId in getTagScoresForMovieModal

frontend/reel-rating-display-service/src/main/webapp/index.html, frontend/reel-rating-display-service/src/main/webapp/js/home.js
Fixes an issue with the show more modal where tags were not unique and could show up repeatedly. Also fixes issue #202 by removing the pre-filled information.
=> Frontend Polish

backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/DatabaseController.java
Added javadocs and other comments to the database controllers to improve readability.
=> Database Controller cleanup

backend/reel-rating-actor-data-service/src/main/java/edu/oswego/cs/rest/ActorDataService.java, backend/reel-rating-movie-data-service/src/main/java/edu/oswego/cs/rest/MovieDataService.java, backend/reel-rating-rating-data-service/src/main/java/edu/oswego/cs/rest/RatingDataService.java, backend/reel-rating-review-data-service/src/main/java/edu/oswego/cs/rest/ReviewDataService.java, backend/reel-rating-search-service/src/main/java/edu/oswego/cs/rest/SearchService.java
This was done to facilitate websocket functionality.
=> The use of cookies is removed in favor of sending sessions keys
